import path from 'node:path'
import fs from 'node:fs/promises'
import fg from 'fast-glob'
import type { Plugin, ViteDevServer } from 'vite'
import type { ResolvedConfig, UserConfig } from '../types'

const VIRTUAL_BOARDS = 'virtual:open-canvas/boards'
const VIRTUAL_CONFIG = 'virtual:open-canvas/config'
const RESOLVED_PREFIX = '\0'

const BOARD_GLOB = '*/index.{tsx,jsx,ts,js}'
const KEBAB = /^[a-z][a-z0-9-]*$/

export interface OpenCanvasPluginOptions extends UserConfig {
  /** 框架根（用户工程根）。Vite 会注入。 */
  root?: string
}

/**
 * 发现 `boards/<id>/index.{tsx,jsx,ts,js}` 并通过虚拟模块暴露：
 *
 * ```ts
 * import boards from 'virtual:open-canvas/boards'
 * boards['intro']() // => Promise<{ default: BoardModule }>
 * ```
 *
 * 增/删 board 时通过 `chokidar` + `server.moduleGraph.invalidateModule` 触发 HMR。
 */
export function openCanvasPlugin(options: OpenCanvasPluginOptions = {}): Plugin {
  let resolved: ResolvedConfig
  let server: ViteDevServer | undefined

  return {
    name: 'open-canvas',
    enforce: 'pre',

    async config(userConfig) {
      const root = options.root ?? userConfig.root ?? process.cwd()
      resolved = await resolveConfig(root, options)
      return {
        resolve: {
          alias: {
            '@open-canvas/runtime': '@open-canvas/core/runtime',
          },
        },
        define: {
          __OPEN_CANVAS_INSPECTOR__: JSON.stringify(resolved.inspector),
        },
      }
    },

    configureServer(s) {
      server = s
      const watcher = s.watcher
      const boardsRoot = path.resolve(resolved.root, resolved.boardsDir)
      watcher.add(boardsRoot)
      const invalidate = () => {
        const m = s.moduleGraph.getModuleById(`${RESOLVED_PREFIX}${VIRTUAL_BOARDS}`)
        if (m) s.moduleGraph.invalidateModule(m)
        s.ws.send({ type: 'full-reload' })
      }
      const onFsEvent = (file: string) => {
        if (file.startsWith(boardsRoot) && /index\.(t|j)sx?$/.test(file)) invalidate()
      }
      watcher.on('add', onFsEvent)
      watcher.on('unlink', onFsEvent)
    },

    resolveId(id) {
      if (id === VIRTUAL_BOARDS) return RESOLVED_PREFIX + VIRTUAL_BOARDS
      if (id === VIRTUAL_CONFIG) return RESOLVED_PREFIX + VIRTUAL_CONFIG
      return null
    },

    async load(id) {
      if (id === RESOLVED_PREFIX + VIRTUAL_BOARDS) {
        const entries = await discoverBoards(resolved)
        const lines = entries.map((e) => {
          // 用绝对路径，Vite 会解析为模块图节点
          return `  ${JSON.stringify(e.id)}: () => import(${JSON.stringify(e.absPath)}),`
        })
        return [
          '// generated by @open-canvas/core',
          'const boards = {',
          ...lines,
          '}',
          'export default boards',
        ].join('\n')
      }
      if (id === RESOLVED_PREFIX + VIRTUAL_CONFIG) {
        return `export default ${JSON.stringify(serializableConfig(resolved))}`
      }
      return null
    },

    handleHotUpdate(ctx) {
      // 当 board 自身的 index.tsx 改动时，让 viewer 自然 HMR；这里不需特别处理。
      void server
      return ctx.modules
    },
  }
}

interface DiscoveredBoard {
  id: string
  absPath: string
}

async function discoverBoards(cfg: ResolvedConfig): Promise<DiscoveredBoard[]> {
  const boardsRoot = path.resolve(cfg.root, cfg.boardsDir)
  try {
    await fs.access(boardsRoot)
  } catch {
    return []
  }
  const matches = await fg(BOARD_GLOB, { cwd: boardsRoot, onlyFiles: true })
  const out: DiscoveredBoard[] = []
  for (const rel of matches) {
    const id = rel.split('/')[0]
    if (!id || !KEBAB.test(id)) continue
    out.push({ id, absPath: path.join(boardsRoot, rel) })
  }
  out.sort((a, b) => a.id.localeCompare(b.id))
  return out
}

async function resolveConfig(root: string, options: UserConfig): Promise<ResolvedConfig> {
  // 尝试加载 open-canvas.config.{ts,js,mjs}（dev 时由 Vite 处理；这里仅做合并）
  const userFromFile = await tryLoadUserConfigFile(root)
  const merged: UserConfig = { ...userFromFile, ...options }
  const isDev = process.env.NODE_ENV !== 'production'
  return {
    root,
    boardsDir: merged.boardsDir ?? 'boards',
    port: merged.port ?? 5173,
    title: merged.title ?? 'open-canvas',
    inspector: merged.inspector ?? isDev,
  }
}

async function tryLoadUserConfigFile(root: string): Promise<UserConfig> {
  for (const name of ['open-canvas.config.ts', 'open-canvas.config.js', 'open-canvas.config.mjs']) {
    const p = path.join(root, name)
    try {
      await fs.access(p)
      // 让 Vite 使用 esbuild 加载；为避免在插件 init 阶段循环依赖，这里只读取空对象。
      // 真正的字段合并放在 dev/build 时由 CLI 完成（见 cli/dev.ts）。
      return {}
    } catch {}
  }
  return {}
}

function serializableConfig(cfg: ResolvedConfig) {
  const { root: _root, ...rest } = cfg
  return rest
}

export type { ResolvedConfig, UserConfig }
